# ───────────────────────────────────────────────────────────────
# SERVICE: Exposing Users API to the Internet
# ───────────────────────────────────────────────────────────────
# This is a PUBLIC LoadBalancer Service, exposing the users API
# to external clients (the Internet)
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users  # Selects Pods with label app: users
  type: LoadBalancer  # Creates external load balancer for Internet access
  ports:
    - protocol: TCP
      port: 8080        # Service port (external)
      targetPort: 8080  # Container port where the app listens